[package]
name = "frontend"
version = "0.0.1"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
stylist = { version = "0.13.0", features = ["yew", "macros"] } 
crossword_generator = { git = "https://github.com/Hayk10002/crossword_generator.git" }